export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const HOME_ROUTE = '/'
export const REGISTRATION_ROUTE = '/registration'
export const COURSE_ROUTE = '/course'
export const FEEDBACK_ROUTE = '/feedback'
export const REVIEWS_ROUTE = '/reviews'